name: hear2learn
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+12

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.2

  audio_service: ^0.7.1
  cached_network_image: ^2.0.0-rc.1
  connectivity: ^0.4.2
  dio: ^1.0.13
  easy_debounce: ^1.0.1
  firebase_analytics: ^5.0.9
  flushbar:
    git:
      url: https://github.com/AndreHaueisen/flushbar
      ref: dev_version
  flutter_cache_manager: any
  flutter_html: ^0.8.2
  flutter_inapp_purchase: ^2.0.6
  flutter_pagewise: ^1.2.2
  flutter_redux: ^0.5.2
  http: any
  intl: any
  jaguar_orm: any
  jaguar_query_sqflite: ^2.2.5
  just_audio: ^0.1.3
  moor: ^2.4.2
  moor_ffi: ^0.4.0
  moor_mysql:
    path: ./packages/moor_mysql
  package_info: ^0.4.0+16
  path: ^1.6.2
  path_provider: ^1.5.1
  percent_indicator: ^1.0.13
  redux: ^3.0.0
  redux_thunk: ^0.2.1
  share: ^0.6.0
  shared_preferences: ^0.4.3
  timeago: ^2.0.9
  url_launcher: 5.0.2
  uuid: ^2.0.0
  webfeed: ^0.4.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  flutter_launcher_icons: "^0.7.0"
  moor_generator: ^2.4.0
  #jaguar_orm_gen: any
  screenshots: ^0.1.6
  test: any


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/data/podcasts.sqlite3
   - images/01--default-fadein-image.jpg
   - images/02--default-fadein-image.jpg
   - images/03--default-fadein-image.jpg
   - images/04--default-fadein-image.jpg
   - images/05--default-fadein-image.jpg
   - images/06--default-fadein-image.jpg
   - images/07--default-fadein-image.jpg
   - images/08--default-fadein-image.jpg
   - images/drawer-header--balloons.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Italic.ttf
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-SemiBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
