name: moor_mysql
description: MySQL support for moor
version: 1.0.0
author: Simon Binder <oss@simonbinder.eu>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  moor: ^2.0.0
  sqljocky5: ^2.2.0

dev_dependencies:
  test: ^1.6.0

dependency_overrides:
  moor:
    path: ../../moor